name: Build Windows images

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build2019:
    strategy:
      matrix:
        include:
          - stunnel_version: '5.70'
            stunnel_sha256: c50fb79329ddbf095e65ba8817a0249188aa5b25f15557f8504d8f65876034d9
            windows_version: 1809
    runs-on: windows-2019
    permissions:
      contents: read
      packages: write
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      - name: Force build if workflow_dispatch or re-run
        id: force
        if: github.event_name == 'workflow_dispatch' || github.run_attempt != '1'
        run: echo "force=-Force" >> $GITHUB_ENV
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build Docker Hub tag (if needed)
        working-directory: windows
        run: ./build_container.ps1 -ImageNameRoot ${{ secrets.DOCKER_USERNAME }}/windows- -WindowsVersion ${{ matrix.windows_version }} -StunnelVersion ${{ matrix.stunnel_version }} -StunnelSha256 ${{ matrix.stunnel_sha256 }} ${{ steps.force.outputs.force }}
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build GHCR tag (if needed)
        working-directory: windows
        run: ./build_container.ps1 -ImageNameRoot ghcr.io/${{ github.repository_owner }}/windows- -WindowsVersion ${{ matrix.windows_version }} -StunnelVersion ${{ matrix.stunnel_version }} -StunnelSha256 ${{ matrix.stunnel_sha256 }} ${{ steps.force.outputs.force }}
